# Generated by Django 5.2.6 on 2025-09-04 09:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True, verbose_name='شماره شاگرد')),
                ('name', models.CharField(max_length=255, verbose_name='نام شاگرد')),
                ('father_name', models.CharField(max_length=255, verbose_name='نام پدر')),
                ('class_name', models.CharField(max_length=100, verbose_name='صنف')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن')),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='فیس ماهانه')),
                ('registration_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت نام')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روز رسانی')),
            ],
            options={
                'verbose_name': 'شاگرد',
                'verbose_name_plural': 'شاگردان',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ پرداخت')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='مقدار')),
                ('month_year', models.CharField(help_text='فرمت: YYYY-MM', max_length=7, verbose_name='ماه/سال')),
                ('payment_method', models.CharField(choices=[('نقدی', 'نقدی'), ('چک', 'چک'), ('انتقال بانکی', 'انتقال بانکی')], default='نقدی', max_length=20, verbose_name='طریقه پرداخت')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='school_management.student', verbose_name='شاگرد')),
            ],
            options={
                'verbose_name': 'پرداخت فیس',
                'verbose_name_plural': 'پرداخت\u200cهای فیس',
                'ordering': ['-payment_date'],
            },
        ),
    ]
