# Generated by Django 5.2.6 on 2025-09-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='شماره شاگرد'),
        ),
    ]
