# Generated by Django 5.2.6 on 2025-09-04 09:55

from django.db import migrations


def backfill_student_ids(apps, schema_editor):
    Student = apps.get_model('school_management', 'Student')
    # Iterate through students missing student_id and backfill
    for s in Student.objects.filter(student_id__isnull=True).iterator():
        s.student_id = f"STD-{s.pk:06d}"
        s.save(update_fields=['student_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('school_management', '0002_alter_student_student_id'),
    ]

    operations = [
        migrations.RunPython(backfill_student_ids, reverse_code=migrations.RunPython.noop),
    ]
